name: Deploy examples to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'examples/**'

jobs:
  build-examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projects: [
          common,
          paper/box,
          paper/core,
          paper/custom,
          paper/dhl,
          paper/pack,
          paper/pnaic,
          paper/simulacrum,
          velocity
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
      - name: Build html
        run: ./gradlew dokkaHtml --no-daemon --stacktrace
        working-directory: ${{ matrix.projects }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.projects }}
          path: examples/gradle/${{ matrix.projects }}/build/dokka



  deploy-examples:
    runs-on: ubuntu-latest
    needs: [ build-examples ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: public/examples
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          publish_dir: ./public
          full_commit_message: Publish examples